baseURL = "https://behzade.github.io/"
languageCode = "en-us"
title = "Behzad Ehsani"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[outputs]
home = ["HTML", "RSS", "JSON"]

[params.profileMode]
enabled = true
title = "Hi, I'm Behzad."
subtitle = "I'm a backend developer."
[[params.profileMode.buttons]]
name = "About"
url = "/about"

[[params.profileMode.buttons]]
name = "Blog"
url = "/blog"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/BehzadEhs"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/behzade/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/behzade"
